version: "3.9"

services:

  db-produto:
    image: postgres:16-alpine
    container_name: db-produto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produtos
    ports:
      - "5433:5432"
    volumes:
      - pgdata_produto:/var/lib/postgresql/data
    restart: always
    networks:
      - ms-rede

  ms-produto:
    build: .
    container_name: ms-produto
    ports:
      - "8081:8081"
    depends_on:
      - db-produto
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-produto:5432/produtos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: host.docker.internal
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
    restart: always
    networks:
      - ms-rede

volumes:
  pgdata_produto:

networks:
  ms-rede:
    external: true
